### PR TITLE
Fix the UI when a tag was deleted

### LINKED ISSUE #118: Retention rule gone?
Hello,

I’ve created an invisible tag and automatic tagging rule. Then (I think) I’ve created retention rule: selected previously created tag and set to delete files after 30 days and when i clicked create button nothing happened… How to find out if creted rule exist and is active? Now when I try to create this rule again, there is no such tag in search box. I have nextcloud 20.0.9 and Retention 1.9.0.

Greetings,
Martin

### LINKED ISSUE #120: Retention of files does not show current configuration settings
Nextcloud 15.0.2

### Steps to reproduce
1. configure Retention of files for a specific tag and apply
2. configuration does note appear, but tag can't be selected anymore

### Expected behaviour
already configured Retention settings should be visible & it should be possible to delete them

### Actual behaviour
already configured Retention settings are not visible

### Server configuration

**Operating system**:Ubunut 18

**Web server:** Apache

**Where did you install Nextcloud from:**
https://www.techandme.se/nextcloud-vm/

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #120 
Fix #118

### CODE REVIEW

File: lib/Controller/APIController.php [hunk 1]
```diff
@@ -76,6 +78,17 @@ public function getRetentions(): JSONResponse {
 
 		$cursor->closeCursor();
 
+
+		try {
+			$this->tagManager->getTagsByIds($tagIds);
+		} catch (TagNotFoundException $e) {
+			$missingTags = array_map('intval', $e->getMissingTags());
+
+			$result = array_values(array_filter($result, static function (array $rule) use ($missingTags) {
```
Comment (CarlSchwan) [inline lib/Controller/APIController.php:87]:
```suggestion
			$result = array_values(array_filter($result, static function (array $rule) use ($missingTags): bool {
```

**Review by CarlSchwan — APPROVED** [review]
