### PR TITLE
Fixed type error with adding new retention rule

### LINKED ISSUE #172: Exception when trying to set up retention
When I try to setup a new retention rule, it seems to work.
The UI shows the rule, however it is impossible to delete it and when refreshing the UI, the rule is gone.
I checked the DB, the retention table is empty.

Eventually I managed to catch an exception in the log:

`
 {"Exception":"Exception","Message":"OCA\\Files_Retention\\Controller\\APIController::addRetention(): Argument #1 ($tagid) must be of type string, int given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/html/custom_apps/files_retention/lib/Controller/APIController.php' line 82","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Retention\\Controller\\APIController"},"addRetention"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Retention\\Controller\\APIController","addRetention",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"files_retention.API.addRetention"}]},{"file":"/var/www/html/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/files_retention/api/v1/retentions"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"TypeError","Message":"OCA\\Files_Retention\\Controller\\APIController::addRetention(): Argument #1 ($tagid) must be of type string, int given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"addRetention","class":"OCA\\Files_Retention\\Controller\\APIController","type":"->","args":[3,0,10,0]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Retention\\Controller\\APIController"},"addRetention"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Retention\\Controller\\APIController"},"addRetention"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Retention\\Controller\\APIController","addRetention",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"files_retention.API.addRetention"}]},{"file":"/var/www/html/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/files_retention/api/v1/retentions"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/files_retention/lib/Controller/APIController.php","Line":82},"CustomMessage":"--"}}
`

Retention version: 1.13.1
Nextcloud Version: 24.0.0

### LINKED ISSUE #175: Unable to add retention rule
### Steps to reproduce
1. As admin User go to /index.php/settings/admin/workflow
2. Try to create a retention rule
3. The new rule is shown but not saved. Reloading the page makes the created rule disappear. 

### Expected behaviour
The rule should be saved.

### Actual behaviour
Nothing is saved.

### Server configuration
**Operating system**: Ubuntu 20.04
**Web server:** Apache 2.4.41-4ubuntu3.11
**Database:** mariadb-server-10.3
**PHP version:** PHP 7.4.3-4ubuntu2.12
**Nextcloud version:** 24.0.2
**Where did you install Nextcloud from:** 
**List of activated apps:** user
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.0
  - files_antivirus: 3.3.0
  - files_automatedtagging: 1.14.0
  - files_pdfviewer: 2.5.0
  - files_retention: 1.13.1
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_saml: 5.0.1
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - dashboard: 7.4.0
  - encryption
  - files_external
  - user_ldap

#### Nextcloud log (data/owncloud.log)
```
{"reqId":"xxx","level":3,"time":"June 22, 2022 08:46:56","remoteAddr":"xxx","user":"admin","app":"index","method":"POST","url":"/index.php/apps/files_retention/api/v1/retentions","message":"Argument 1 passed to OCA\\Files_Retention\\Controller\\APIController::addRetention() must be of the type string, int given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/nextcloud/apps/files_retention/lib/Controller/APIController.php' line 82","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0","version":"24.0.2.1","exception":{"Exception":"Exception","Message":"Argument 1 passed to OCA\\Files_Retention\\Controller\\APIController::addRetention() must be of the type string, int given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/nextcloud/apps/files_retention/lib/Controller/APIController.php' line 82","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\Files_Retention\\Controller\\APIController::addRetention() must be of the type string, int given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"addRetention","class":"OCA\\Files_Retention\\Controller\\APIController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/files_retention/lib/Controller/APIController.php","Line":82},"CustomMessage":"--"}}
```

### PR DESCRIPTION
**Pull request by nickvergessen**
Repushing #174  so CI runs

Fix #175 
Fix #172

### CODE REVIEW

**Review by CarlSchwan — APPROVED** [review]

File: lib/BackgroundJob/RetentionJob.php [hunk 1]
```diff
@@ -85,7 +85,7 @@ public function run($argument): void {
 		// Validate if tag still exists
 		$tag = $argument['tag'];
 		try {
-			$this->tagManager->getTagsByIds($tag);
+			$this->tagManager->getTagsByIds((string) $tag);
```
Comment (CarlSchwan) [inline lib/BackgroundJob/RetentionJob.php:88]: should this maybe also be done in the createNamedParameter call? or once line 86

Comment (nickvergessen) [reply lib/BackgroundJob/RetentionJob.php:88]: No, because the retention code is int based. Only the TagManager code is string based although it casts to int afterwards itself as the DB is int for oc_systemtags* tables as well...
