### PR TITLE
Check all nodes and all mountpoints for delete permissions

### LINKED ISSUE #101: Files are not deleted
Hi everybody,

I wanna use the retention app. The configuration is correct, but files are not deleted.

### Steps to reproduce
1. Uploaded files get automatically a tag through the workflow app
2. 24 hours before the planned deletion I get a notification, that the file will be deleted in 24 hours
3. But file will be not deleted

### Server configuration
Operating system: Ubuntu 18.01
Web server: Apache 2.4
Database: MariaDB 10.1
PHP version: 7,2
Nextcloud version: 18.0.10

Where did you install Nextcloud from:
official website

Best regards!

### LINKED ISSUE #137: Files can not be deleted by the retention job if the file is not deletable in the user mount point
The retention job only takes into account [the first node](https://github.com/nextcloud/files_retention/blob/d5f72e8713ad83c699ee4148e6340877d4d82a18/lib/BackgroundJob/RetentionJob.php#L222) of [the first mount point](https://github.com/nextcloud/files_retention/blob/d5f72e8713ad83c699ee4148e6340877d4d82a18/lib/BackgroundJob/RetentionJob.php#L200) of a file to be deleted. If that node is not deletable the retention job will fail to delete it, even if it would be deletable when using a node from another mount point.

Moreover, in some cases the retention job may not be able to delete a file even if there is a single mount point if the file is not deletable in that mount point (for example, if it is in a group folder without delete permissions).

## Steps to reproduce (scenario 1)

- As an admin, create users _user0_ and _user1_
- Log in as _user0_
- Open the Files app
- Create a folder
- Share the folder with _user1_
- Remove delete permissions from the share
- Open the folder
- Upload an old file (a file with an mtime from months or years ago)
- Add a tag _deleteTest_ to that file
- Log out
- Log in as _user1_ (so the mount point for the shared folder is created)
- Log out
- As an admin, create user _user2_
- Transfer ownership of files from _user0_ to _user2_ with `occ files:transfer-ownership user0 user2`
- Delete _user0_ with `occ user:delete user0` (so the mount point for the shared folder becomes the first one for the file)
- Log in as _user1_
- Do NOT log out (so the shared storage for the shared folder is kept "alive"; this needs to be done after the share was transferred)
- As an admin, open the Flow admin settings
- Create a new retention job to delete files with tag _deleteTest_ and a modification time older than 10 days
- Set debug level for Nextcloud logs with `occ config:system:set loglevel --type integer --value 0`
- Wait patiently until the retention job runs or force its execution with `occ background-job:execute --force-execute XXX` (requires https://github.com/nextcloud/server/pull/27217)
  - The following SQL query can be used to find out the job ID; if there is more than one retention job look for the matching tag ID in the arguments: `SELECT id, argument FROM oc_jobs WHERE class LIKE "%Files_Retention%"`

### Expected behaviour

The file is deleted.

### Actual behaviour

The file is not deleted. Nextcloud logs show a `NotPermittedException` when trying to delete the file with the retention job.

## Steps to reproduce (scenario 2)

- As an admin, create user _user0_ and add that user to group _group0_
- Install and enable the _groupfolders_ app
- Create a group folder for _group0_ and remove the _Delete_ permission
  - It seems that group folders admin UI does not work yet with NC 23, so you may need to use OCC commands to associate a group with a group folder (`occ groupfolders:group {GROUP_FOLDER_ID} group0 write share`)
- Log in as _user0_
- Open the Files app
- Open the group folder
- Upload an old file (a file with an mtime from months or years ago) inside the group folder
- Add a tag _deleteTest_ to the file
- As an admin, open the Flow admin settings
- Create a new retention job to delete files with tag _deleteTest_ and a modification time older than 10 days
- Set debug level for Nextcloud logs with `occ config:system:set loglevel --type integer --value 0`
- Wait patiently until the retention job runs or force its execution with `occ background-job:execute --force-execute XXX` (requires https://github.com/nextcloud/server/pull/27217)
  - The following SQL query can be used to find out the job ID; if there is more than one retention job look for the matching tag ID in the arguments: `SELECT id, argument FROM oc_jobs WHERE class LIKE "%Files_Retention%"`

### Expected behaviour

The file is deleted.

### Actual behaviour

The file is not deleted. Nextcloud logs show a `NotPermittedException` when trying to delete the file with the retention job.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #137
Fix #101

### CODE REVIEW

File: lib/BackgroundJob/RetentionJob.php [hunk 1]
```diff
@@ -197,8 +199,21 @@ private function checkFileId(int $fileId): Node {
 			throw new NotFoundException("No mount points found for file $fileId");
 		}
 
-		$mountPoint = array_shift($mountPoints);
+		foreach ($mountPoints as $mountPoint) {
+			try {
+				return $this->getDeletableNodeFromMountPoint($mountPoint, $fileId);
+			} catch (NotPermittedException $e) {
+				// Check the next mount point
+				$this->logger->debug('Mount point ' . $mountPoint->getMountId() . ' has no delete permissions for file ' . $fileId);
```
Comment (danxuliu) [inline lib/BackgroundJob/RetentionJob.php:207]: `ICachedMountInfo::getMountId()` (inherited by `ICachedMountFileInfo`) [can be null](https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/public/Files/Config/ICachedMountInfo.php#L67), so it would be better to use [`ICachedMountInfo::getMountPoint()`](https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/public/Files/Config/ICachedMountInfo.php#L59) instead (or in addition to) to always get a value.

File: lib/BackgroundJob/RetentionJob.php [hunk 2]
```diff
@@ -219,7 +234,14 @@ private function checkFileId(int $fileId): Node {
 			throw new NotFoundException('No node for file ' . $fileId . ' and user ' . $userId);
 		}
 
-		return array_shift($nodes);
+		foreach ($nodes as $node) {
+			if ($node->getPermissions() & \OCP\Constants::PERMISSION_DELETE) {
```
Comment (danxuliu) [inline lib/BackgroundJob/RetentionJob.php:238]: I would use `$node->isDeletable()` instead for simplicity (unless there is any case in which they give different results, which I do not know).

File: lib/BackgroundJob/RetentionJob.php [hunk 3]
```diff
@@ -219,7 +234,14 @@ private function checkFileId(int $fileId): Node {
...
+				return $node;
+			}
+			$this->logger->debug('Mount point has access to node ' . $node->getId() . ' but permissions are ' . $node->getPermissions());
```
Comment (danxuliu) [inline lib/BackgroundJob/RetentionJob.php:241]: I would add the mount point information too to this message for the sake of completeness.

**Review by danxuliu — CHANGES_REQUESTED** [review]
CI is not happy (unit tests need to be adjusted).

With the updated behaviour it might be good to change [_Node with id $fileId was not found_](https://github.com/nextcloud/files_retention/blob/d5f72e8713ad83c699ee4148e6340877d4d82a18/lib/BackgroundJob/RetentionJob.php#L165) to align better with the exception message when the nodes are actually found but they are not deletable (_No mount point with delete permissions found for file $fileId_). Maybe something like _Deletable node with id $fileId was not found_ or _Node with id $fileId was not found or is not deletable_.

Besides that, tested and works :+1: (when at least one node is deletable).

If there is no deletable node for the file id then the retention app will not be able to delete the file. On one hand it makes sense, although on the other hand, given that the app is not tied to any user, only a tag, it could be expectable that it can delete the files anyway. Should I extract that case from #137 to a different issue?

File: lib/BackgroundJob/RetentionJob.php (hunk 1 above)
Comment (nickvergessen) [reply lib/BackgroundJob/RetentionJob.php:207]: but getMountPoint is a path unique to the user and therefor not as helpful iirc.
I will instead add a fallback for null

Comment (danxuliu) [reply lib/BackgroundJob/RetentionJob.php]: From what I could see `getMountPoint()` includes the user name and the path in that user's filesystem, so that information would help in case debugging is needed, so I would print that instead of `null` :-)

**Review by danxuliu — APPROVED** [review]
